### ISSUE TITLE
First release number is 1.x-1.x

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/block_disabler#1]
About to give this a spin. Just noticed that the first release is 1.x-1.x. Shouldn't it be something like 1.x-0.0.1 or 1.x-1.0.0 instead?

**Comment by docwilmot** [comment]
I think this is the second time you've caught me doing this. Will fix shortly

**Comment by klonos** [comment]
No worries, I am the contrib "sentinel". That's why I'm here for 😉

**Comment by klonos** [comment]
Fixed it for you. I hope you don't mind.
